{ pkgs, lib, ... }:

let
  ports = import ./_port-definitions.nix;
in
{
  networking.firewall.allowedTCPPorts = with ports.tcp.flippydrive; [
    server
    ftp
  ];
  virtualisation.oci-containers.containers."flippydrive-server" = {
    image = "offbroadway/flippydrive-server:v1.4.6";
    volumes = [ "/mnt/hdd-01/gamecube:/data:rw" ];
    ports = [
      "${toString ports.tcp.flippydrive.server}:7031/tcp"
      "${toString ports.tcp.flippydrive.ftp}:7021/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=flippydrive-server"
      "--network=flippydrive-server_default"
    ];
  };
  systemd.services."podman-flippydrive-server-flippydrive-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [ "podman-network-flippydrive-server_default.service" ];
    requires = [ "podman-network-flippydrive-server_default.service" ];
    partOf = [ "podman-compose-flippydrive-server-root.target" ];
    wantedBy = [ "podman-compose-flippydrive-server-root.target" ];
  };

  # Networks
  systemd.services."podman-network-flippydrive-server_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f flippydrive-server_default";
    };
    script = ''
      podman network inspect flippydrive-server_default || podman network create flippydrive-server_default
    '';
    partOf = [ "podman-compose-flippydrive-server-root.target" ];
    wantedBy = [ "podman-compose-flippydrive-server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-flippydrive-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
