{
  den,
  lib,
  kadachi-lib,
  ...
}:
let
  inherit (kadachi-lib) mkOpt;
in
{
  den.schema.host =
    { host, ... }:
    {
      options.services.koito = with lib.types; {
        domain = mkOpt str "koito.${host.services.baseDomain}";
      };
    };

  kasane.services._.koito = den.lib.take.exactly (
    { host }:
    {
      nixos =
        let
          koitoPort = 4110;
        in
        { config, pkgs, ... }:
        {
          virtualisation.oci-containers.containers."koito" = {
            image = "gabehf/koito:v0.1.6";
            environment = {
              "KOITO_ALLOWED_HOSTS" = host.services.koito.domain;
              "KOITO_ENABLE_LBZ_RELAY" = "true";
              "KOITO_LBZ_RELAY_URL" = "https://api.listenbrainz.org/1";
              "KOITO_DEFAULT_THEME" = "catppuccin";
            };
            environmentFiles = [ config.sops.templates."koito.env".path ];
            volumes = [ "/mnt/hdd-01/koito:/etc/koito:rw" ];
            ports = [ "${toString koitoPort}:4110/tcp" ];
            log-driver = "journald";
            extraOptions = [
              "--network-alias=koito"
              "--network=koito_default"
            ];
          };

          systemd = {
            services = {
              "podman-koito" = {
                serviceConfig = {
                  Restart = lib.mkOverride 90 "always";
                };
                after = [ "podman-network-koito_default.service" ];
                requires = [ "podman-network-koito_default.service" ];
                partOf = [ "podman-compose-koito-root.target" ];
                wantedBy = [ "podman-compose-koito-root.target" ];
              };
              "podman-network-koito_default" = {
                path = [ pkgs.podman ];
                serviceConfig = {
                  Type = "oneshot";
                  RemainAfterExit = true;
                  ExecStop = "podman network rm -f koito_default";
                };
                script = ''
                  podman network inspect koito_default || podman network create koito_default
                '';
                partOf = [ "podman-compose-koito-root.target" ];
                wantedBy = [ "podman-compose-koito-root.target" ];
              };
            };
            targets."podman-compose-koito-root" = {
              unitConfig = {
                Description = "Root target generated by compose2nix.";
              };
              after = [ "postgresql.service" ];
              requires = [ "postgresql.service" ];
              wantedBy = [ "multi-user.target" ];
            };
          };

          services = {
            nginx.virtualHosts.${host.services.koito.domain} = {
              locations."/".proxyPass = "http://localhost:${toString koitoPort}";
              forceSSL = true;
              useACMEHost = host.services.baseDomain;
            };

            postgresql = {
              ensureDatabases = [ "koito" ];
              ensureUsers = [
                {
                  name = "koito";
                  ensureDBOwnership = true;
                }
              ];
            };
          };

          sops = {
            secrets = {
              "koito/database_url" = { };
              "koito/listenbrainz_token" = { };
            };
            templates."koito.env".content = ''
              KOITO_DATABASE_URL=${config.sops.placeholder."koito/database_url"}
              KOITO_LBZ_RELAY_TOKEN=${config.sops.placeholder."koito/listenbrainz_token"}
            '';
          };
        };
    }
  );
}
